config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/cocktails')

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews

  validates :name, presence: true, uniqueness: true

  def get_average_stars(stars)
    total_stars = @cocktail.reviews.map { |s| s.stars.nil? ? 0 : s.stars }
    @average_stars = total_stars.inject { |sum, el| sum + el } / total_stars.count
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :ingredient, scope: :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true

  NAMES = Ingredient.order(:name).all.map { |ingredient| [ingredient.name, ingredient.id] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :name, presence: true
  validates :content, presence: true

  STARS = (1..5).to_a
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new

    # total_stars = @cocktail.reviews.map { |s| s.stars.nil? ? 0 : s.stars }
    # @average_stars = total_stars.inject { |sum, el| sum + el } / total_stars.count
    # raise
  end

  def show
    @dose = Dose.new
    @ingredient = Ingredient.new
    @review = Review.new
    # raise
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      # Redirect to new doses
      redirect_to cocktail_path(@cocktail)
    else
      render :index
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :image_url, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @ingredient = Ingredient.new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # @dose.ingredient = Ingredient.find(params[:ingredient][:name])
    @dose.ingredient = Ingredient.find(params[:dose][:ingredient_id].to_i)
    # raise
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render template: 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(Cocktail.find(@dose.cocktail_id))
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description)
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail

    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render template: 'cocktails/show'
    end
    # raise
  end

  private

  def review_params
    params.require(:review).permit(:name, :content, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h1>Mister Cocktails</h1>
  <div class="row">

  <% @cocktails.each do |cocktail| %>
    <%
      if cocktail.photo.url
        photo = cl_image_path cocktail.photo, width: 400, crop: :fill
      end
    %>

    <%
      stars_array = cocktail.reviews.map { |s| s.stars.nil? ? 0 : s.stars }
      if stars_array.count > 0
        total_stars = stars_array.inject { |sum, el| sum + el }
        if total_stars > 0
          average_stars = (total_stars / stars_array.count).round
        else
          average_stars = 1
        end
      else
        average_stars = 1
      end
    %>

    <div class="col-xs-12 col-sm-4">
    <div class="card-container">
      <a class="card-link" href="#" ></a>
      <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= photo %>');background-size: cover;">
        <div class="card-category"><h4><%= cocktail.name %></h4></div>
      </div>
      <div class="card-body">
        <% if cocktail.doses %>
          <ul class="index-doses">
          <% cocktail.doses.first(3).each do |dose| %>
            <li><%= dose.ingredient.name %><span class="middot">&middot;</span><%= dose.description %></li>
          <% end %>
          </ul>
        <% end %>
        <div class="stars">
          <% 5.times.each do |count| %>
            <% if average_stars > count %>
              <i class="fas fa-glass-martini-alt star"></i>
            <% else %>
              <i class="fas fa-glass-martini-alt unstar"></i>
            <% end %>
          <% end %>
        </div>
              <!-- <i class="fas fa-glass-martini-alt star"></i><i class="fas fa-glass-martini-alt star"></i><i class="fas fa-glass-martini-alt star"></i><i class="fas fa-glass-martini-alt unstar"></i><i class="fas fa-glass-martini-alt unstar"></i></div> -->
      </div>
    </div>
  </div>
  <% end %>

</div>
<span class="new-cocktail-button">New Cocktail</span>
<div class="create-cocktail">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name, style: "height: 5px;" %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit %>
  <% end %>
</div>
</div>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="show-container">
  <h1><%= @cocktail.name %></h1>

  <div><%= link_to "Back to Cocktails", cocktails_path %></div>

  <%
    if @cocktail.photo.url
      photo = cl_image_path @cocktail.photo, width: 400, crop: :fill
    end
  %>
  <div class="cocktail-flex-box">
    <div class="cocktail-container">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= photo %>');background-size: cover; background-position: center;">
        <div class="card-category"><h4><%= @cocktail.name %></h4></div>
      </div>
      <div class="card-body cocktail-card-body">
        <% if @cocktail.doses %>
          <ul class="index-doses">
          <% @cocktail.doses.each do |dose| %>
            <li><%= dose.ingredient.name %><span class="middot">&middot;</span><%= dose.description %> <span style="float: right"><%= link_to "Delete", dose_path(dose), method: 'delete' %></span></li>
          <% end %>
          </ul>
        <% end %>
        <div class="ingredients-form">
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient, collection: Ingredient.order(name: :asc), prompt: "Choose an Ingredient" %>
          <%= f.input :description, label: 'Dose', class: 'form-control-sm' %>
          <%= f.submit %>
        <% end %>
        </div>
      </div>
    </div>

    <div class="cocktail-container reviews-container">
      <div class="review-section">
        <h3>Add Review</h3>
        <%= simple_form_for [@cocktail, @review] do |f| %>
          <%= f.input :name, class: 'form-control-sm' %>
          <%= f.input :content, class: 'form-control' %>
          <%= f.input :stars, collection: Review::STARS, class: 'form-control', selected: 1 %>
          <%= f.submit %>
        <% end %>
      </div>

      <h3>Reviews</h3>
      <% @cocktail.reviews.order(updated_at: :desc).each do |review| %>
        <div class="review-section">
          <div class="review-header">
            <span class="review-name"><%= review.name %></span>
            <span class="review-stars">
              <% 5.times.each do |count| %>
                <% if review.stars && review.stars > count %>
                  <i class="fas fa-glass-martini-alt star"></i>
                <% else %>
                  <i class="fas fa-glass-martini-alt unstar"></i>
                <% end %>
              <% end %>
            </span>
          </div>
          <div class="review-content">
            <p><%= review.content %></p>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<h1>New Cocktail</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= simple_fields_for @ingredient do |i| %>
    <%= i.input :name %>
  <% end %>
    <%= f.input :description %>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mister Cocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic|Poiret+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>